url: 'https://anpigon.github.io'
baseurl: ''
lang: ko
title: 안피곤의 블로그
description: |
  안피곤의 블로그
tagline: |
  시간이 천천히 갔으면 좋겠다.
keywords: []
logo: /assets/icons/icon.png
author:
  picture: /assets/img/me.npg
  social:
    email: 'mailto:markan82@gmail.com'
    download: ''
  name: anpigon
  email: markan82@gmail.com
copyright: © 2019. All rights reserved.
permalink: pretty
paginate: 5
paginate_path: '/page-:num/'
defaults:
  - scope:
      type: posts
    values:
      comments: true
accent_image: /assets/img/blog_background1.png
accent_color: '#4fb1ba'
google_fonts: 'Roboto+Slab:700|Noto+Serif+KR:400,400i,700,700i'
font: 'Noto Serif KR, Helvetica, Arial, sans-serif'
font_heading: 'Roboto Slab, Helvetica, Arial, sans-serif'
disqus: anpigon-github-io
google_analytics: UA-20589042-10
hydejack:
  post_addons:
    - about
    - newsletter
    - related
  project_addons:
    - about
    - newsletter
    - other
  no_google_fonts: false
  no_mark_external: false
  no_push_state: false
  no_drawer: false
  no_inline_css: false
  no_break_layout: false
  no_structured_data: false
  no_theme_color: false
  use_lsi: false
collections:
  featured_categories:
    permalink: '/category/:name/'
    output: true
  featured_tags:
    permalink: '/tag/:name/'
    output: true
  projects:
    permalink: '/projects/:path/'
    output: true
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
remote_theme: qwtel/hydejack@gem-7.5.0
optional_front_matter:
  remove_originals: true
readme_index:
  remove_originals: true
relative_links:
  collections: true
titles_from_headings:
  strip_title: true
  collections: true
kramdown:
  footnote_backlink: '&#x21a9;&#xfe0e;'
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true
compress_html:
  comments:
    - '<!-- '
    - ' -->'
  clippings: all
  endings: all
sass:
  style: compressed
feed:
  path: atom.xml
jekyll_admin:
  hidden_links:
    - projects
show_drafts: true
